### ISSUE TITLE
Clean up error message when API credentials are incorrect

### ISSUE THREAD

**Issue by JamesPiechota** [YellowPay/yellow-wordpress#3]
Right now when the API credentials are incorrect an error message like the following is displayed:

`Fatal error: Cannot use object of type GuzzleHttp\Message\Response as array in /path/to/woocommerce-yellow.php on line 183`

We should show something more helpful.

**Comment by mahmoud200m** [comment]
done

**Comment by mahmoud200m** [comment]
fixed
